### Function: Healthcheck
GET http://127.0.0.1:3000/api/healthcheck


### Function: Create Goal 200
POST http://127.0.0.1:3000/api/goals/create
Content-type: application/json

{
  "title": "Ler 10 páginas",
  "desiredWeeklyFrequency": 3
}


### Function: Create Goal 500
POST http://127.0.0.1:3000/api/goals/create
Content-type: application/json

{
  "title": "Ler 10 páginas",
  "desiredWeeklyFrequency": "string is invalid type"
}


### Function: Get Week Pending Goals 200
GET http://127.0.0.1:3000/api/goals/get-pendings


### Function: Get Week Pending Goals 200
POST http://127.0.0.1:3000/api/goals/get-completions
Content-type: application/json

{
  "goalId": "t4fsxs9dp284afht3uuyt74q"
}