name: nlw-pocket

services:

  backend:
    build:
      context: ./../../../backend
      dockerfile: .config/docker/Dockerfile
    # env_file: ./../../../backend/.config/env/.env
    environment:
      - HTTP_PORT=3000
      - HTTP_HOST=0.0.0.0
      - DATABASE_URL=postgresql://docker:docker@postgresql:5432/inorbit
    ports:
      - '3000:3000'
    volumes:
      - ./../../../backend:/home/node/app
      # Anonymous volume to prevent the node_modules from being overwritten in the host:
      - /home/node/app/node_modules
    networks:
      - pocket-net-stag
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: curl "http://$$HTTP_HOST:$$HTTP_PORT/api/healthcheck"
      start_period: '5s'
      interval: '15s'
      timeout: '5s'
      retries: 5

  postgresql:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    env_file: ./.env
    networks:
      - pocket-net-stag
    healthcheck:
      test: pg_isready --host=127.0.0.1 --port=5432 --dbname=inorbit --username=docker
      start_period: '5s'
      interval: '5s'
      timeout: '5s'
      retries: 5
    # volumes:
    #   - pocket_staging_data:/bitnami/postgresql

volumes:
  pocket_staging_data:

networks:
  pocket-net-stag:
    external: true
